<?= $this->doctype(); ?>
<html lang="en">
<head>
  <meta charset="utf-8">
  <?= $this->headTitle('CleanPhp')->setSeparator(' - ')->setAutoEscape(false) ?>

  <?= $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <?= $this->headLink()
    ->prependStylesheet('/css/application.css')
    ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css') ?>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<?= $this->url('home') ?>">CleanPhp</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <a href="<?= $this->url('customers') ?>">Customers</a>
          </li>
          <li>
            <a href="<?= $this->url('orders') ?>">Orders</a>
          </li>
          <li>
            <a href="<?= $this->url('invoices') ?>">Invoices</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <?= $this->content; ?>
    <hr>
    <footer>
      <p>I'm the footer.</p>
    </footer>
  </div>
  <?= $this->inlineScript() ?>
</body>
</html>
